version: "2"
services:
  wolverine-database:
    build:
      context: wolf-backend-model
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wolf
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: wolverine-database
    image: wolverine-database
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  wolverine-backend:
    build:
      context: wolf-web
      dockerfile: Dockerfile
    depends_on:
      - wolverine-database
      - rabbitmq
    ports:
      - "8080:8080"
    container_name: wolveriner-backend
    restart: always
    image: wolverine-backend
